name: insall package server
run-name: testing of the server 
on: [push]
jobs:
  server-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    env:
       NODE_ENV: 'develepment'
       PORT: '8000'
       DB_HOST: 'localhost'
       DB_NAME: 'marhaba'
       DB_USER: 'root'
       DB_PASS: ''
       MONGO_URI: 'mongodb+srv://abdessamad:azertyui@firstapi.wjgnfv3.mongodb.net/mernjs?retryWrites=true&w=majority'
       JWT_SECRET: '123456789'
       JWT_EXPIRE: '15m'
       EMAIL_HOST: 'smtp.gmail.com'
       EMAIL_PORT: '587'
       EMAIL_USER: 'abdessamadbattal@gmail.com'
       EMAIL_PASS: 'tqbjqjylcvkocjez'
       EMAIL_SECURE: 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm i
      - run: npm test
  client-testing:
    runs-on: ubuntu-latest
    needs: [server-testing]
    defaults:
       run:
        working-directory: ./client
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18.12.1
        - run: npm i
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    needs: [client-testing]
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ftp.jami3a.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
    
